# Codedeploy 는 appspec.yml 파일을 참조하여 배포를 진행한다.
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy/zip/
    overwrite: yes

# 권한 설정
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

# 배포 진행
hooks:
    # 배포 진행
    ApplicationStart:
        - location: deploy.sh
          timeout: 60
          runas: root