cloud:
  aws:
    s3:
      bucket: jipasayo-age
    credentials:
      access-key: AKIAXETUFH7P6HYP4COR
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false