spring:
  profiles:
    include:
      - rds
      - file-logging
      - s3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

logging:
  level:
    root: info # trace<debug<info<warn<error<fatal