cloud:
  aws:
    s3:
      bucket: jipsayo-age
    credentials:
      access-key: AKIAXETUFH7PQXOU7YSQ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false