spring:
  profiles:
    include:
      - rds
      - file-logging
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true

logging:
  level:
    root: info # trace<debug<info<warn<error<fatal